name: test and lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go test ./...
      - uses: golangci/golangci-lint-action@v3
